--
-- PostgreSQL database dump
--

\restrict ldgzxKQJyVKhz7jfcOlAa2SFb9edJcVEmkOMngUf9W0HCvJbXK0e01EshemhIqp

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AssetValuations; Type: TABLE; Schema: public; Owner: maintenance_user
--

CREATE TABLE public."AssetValuations" (
    "AssetValuationId" integer NOT NULL,
    "EquipmentId" integer NOT NULL,
    "ValuationDate" timestamp with time zone NOT NULL,
    "ValuationAmount" numeric(19,4) NOT NULL,
    "CurrencyId" integer NOT NULL,
    "ValuationType" character varying(30) NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."AssetValuations" OWNER TO maintenance_user;

--
-- Name: AssetValuations_AssetValuationId_seq; Type: SEQUENCE; Schema: public; Owner: maintenance_user
--

ALTER TABLE public."AssetValuations" ALTER COLUMN "AssetValuationId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AssetValuations_AssetValuationId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AssetValues; Type: TABLE; Schema: public; Owner: maintenance_user
--

CREATE TABLE public."AssetValues" (
    "AssetValueId" integer NOT NULL,
    "EquipmentId" integer NOT NULL,
    "AcquisitionCost" numeric(19,4) NOT NULL,
    "CurrencyId" integer NOT NULL,
    "AcquisitionDate" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."AssetValues" OWNER TO maintenance_user;

--
-- Name: AssetValues_AssetValueId_seq; Type: SEQUENCE; Schema: public; Owner: maintenance_user
--

ALTER TABLE public."AssetValues" ALTER COLUMN "AssetValueId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AssetValues_AssetValueId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Companies; Type: TABLE; Schema: public; Owner: maintenance_user
--

CREATE TABLE public."Companies" (
    "CompanyId" integer NOT NULL,
    "CompanyCode" character varying(50) NOT NULL,
    "CompanyName" character varying(200) NOT NULL,
    "CountryId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Companies" OWNER TO maintenance_user;

--
-- Name: Companies_CompanyId_seq; Type: SEQUENCE; Schema: public; Owner: maintenance_user
--

ALTER TABLE public."Companies" ALTER COLUMN "CompanyId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Companies_CompanyId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Countries; Type: TABLE; Schema: public; Owner: maintenance_user
--

CREATE TABLE public."Countries" (
    "CountryId" integer NOT NULL,
    "CountryCode" character varying(2) NOT NULL,
    "CountryName" character varying(100) NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Countries" OWNER TO maintenance_user;

--
-- Name: Countries_CountryId_seq; Type: SEQUENCE; Schema: public; Owner: maintenance_user
--

ALTER TABLE public."Countries" ALTER COLUMN "CountryId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Countries_CountryId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Currencies; Type: TABLE; Schema: public; Owner: maintenance_user
--

CREATE TABLE public."Currencies" (
    "CurrencyId" integer NOT NULL,
    "CurrencyCode" character varying(3) NOT NULL,
    "CurrencyName" character varying(100) NOT NULL,
    "Symbol" character varying(10) NOT NULL,
    "DecimalPlaces" smallint NOT NULL,
    "IsDefault" boolean NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Currencies" OWNER TO maintenance_user;

--
-- Name: Currencies_CurrencyId_seq; Type: SEQUENCE; Schema: public; Owner: maintenance_user
--

ALTER TABLE public."Currencies" ALTER COLUMN "CurrencyId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Currencies_CurrencyId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Depreciations; Type: TABLE; Schema: public; Owner: maintenance_user
--

CREATE TABLE public."Depreciations" (
    "DepreciationId" integer NOT NULL,
    "EquipmentId" integer NOT NULL,
    "DepreciationDate" timestamp with time zone NOT NULL,
    "DepreciationAmount" numeric(19,4) NOT NULL,
    "AccumulatedAmount" numeric(19,4) NOT NULL,
    "CurrencyId" integer NOT NULL,
    "Method" character varying(30) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Depreciations" OWNER TO maintenance_user;

--
-- Name: Depreciations_DepreciationId_seq; Type: SEQUENCE; Schema: public; Owner: maintenance_user
--

ALTER TABLE public."Depreciations" ALTER COLUMN "DepreciationId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Depreciations_DepreciationId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Equipment; Type: TABLE; Schema: public; Owner: maintenance_user
--

CREATE TABLE public."Equipment" (
    "EquipmentId" integer NOT NULL,
    "SiteId" integer NOT NULL,
    "EquipmentCode" character varying(50) NOT NULL,
    "EquipmentName" character varying(200) NOT NULL,
    "Description" text,
    "SerialNumber" character varying(100),
    "Manufacturer" character varying(150),
    "ModelNumber" character varying(100),
    "EquipmentStatus" character varying(30) NOT NULL,
    "AcquisitionDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Equipment" OWNER TO maintenance_user;

--
-- Name: Equipment_EquipmentId_seq; Type: SEQUENCE; Schema: public; Owner: maintenance_user
--

ALTER TABLE public."Equipment" ALTER COLUMN "EquipmentId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Equipment_EquipmentId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: InflationIndexes; Type: TABLE; Schema: public; Owner: maintenance_user
--

CREATE TABLE public."InflationIndexes" (
    "InflationIndexId" integer NOT NULL,
    "CountryId" integer NOT NULL,
    "PeriodStart" timestamp with time zone NOT NULL,
    "PeriodEnd" timestamp with time zone NOT NULL,
    "IndexValue" numeric(19,6) NOT NULL,
    "Source" character varying(200),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "CK_InflationIndexes_PeriodRange" CHECK (("PeriodEnd" >= "PeriodStart"))
);


ALTER TABLE public."InflationIndexes" OWNER TO maintenance_user;

--
-- Name: InflationIndexes_InflationIndexId_seq; Type: SEQUENCE; Schema: public; Owner: maintenance_user
--

ALTER TABLE public."InflationIndexes" ALTER COLUMN "InflationIndexId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."InflationIndexes_InflationIndexId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MaintenanceRequests; Type: TABLE; Schema: public; Owner: maintenance_user
--

CREATE TABLE public."MaintenanceRequests" (
    "MaintenanceRequestId" integer NOT NULL,
    "EquipmentId" integer NOT NULL,
    "RequestNumber" character varying(50) NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "Priority" character varying(30) NOT NULL,
    "Status" character varying(30) NOT NULL,
    "RequestedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."MaintenanceRequests" OWNER TO maintenance_user;

--
-- Name: MaintenanceRequests_MaintenanceRequestId_seq; Type: SEQUENCE; Schema: public; Owner: maintenance_user
--

ALTER TABLE public."MaintenanceRequests" ALTER COLUMN "MaintenanceRequestId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MaintenanceRequests_MaintenanceRequestId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sites; Type: TABLE; Schema: public; Owner: maintenance_user
--

CREATE TABLE public."Sites" (
    "SiteId" integer NOT NULL,
    "CompanyId" integer NOT NULL,
    "SiteCode" character varying(50) NOT NULL,
    "SiteName" character varying(200) NOT NULL,
    "CountryId" integer NOT NULL,
    "AddressLine1" character varying(250) NOT NULL,
    "AddressLine2" character varying(250),
    "City" character varying(100) NOT NULL,
    "PostalCode" character varying(30),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Sites" OWNER TO maintenance_user;

--
-- Name: Sites_SiteId_seq; Type: SEQUENCE; Schema: public; Owner: maintenance_user
--

ALTER TABLE public."Sites" ALTER COLUMN "SiteId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sites_SiteId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: maintenance_user
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO maintenance_user;

--
-- Data for Name: AssetValuations; Type: TABLE DATA; Schema: public; Owner: maintenance_user
--

COPY public."AssetValuations" ("AssetValuationId", "EquipmentId", "ValuationDate", "ValuationAmount", "CurrencyId", "ValuationType", "Notes", "CreatedAt") FROM stdin;
1	1	2025-12-31 00:00:00+00	85000.0000	2	Revaluation	Annual asset valuation	2026-09-20 14:03:48.476351+00
2	1	2026-06-30 00:00:00+00	82000.0000	2	Market	Mid-year market valuation	2026-09-20 14:03:48.476351+00
3	2	2025-12-31 00:00:00+00	60000.0000	2	Revaluation	Annual asset valuation	2026-09-20 14:03:48.476351+00
4	3	2025-12-31 00:00:00+00	65000.0000	1	Revaluation	Annual asset valuation	2026-09-20 14:03:48.476351+00
5	4	2025-12-31 00:00:00+00	110000.0000	3	Market	External market valuation	2026-09-20 14:03:48.476351+00
6	5	2026-06-30 00:00:00+00	42000.0000	4	Market	Current market valuation	2026-09-20 14:03:48.476351+00
\.


--
-- Data for Name: AssetValues; Type: TABLE DATA; Schema: public; Owner: maintenance_user
--

COPY public."AssetValues" ("AssetValueId", "EquipmentId", "AcquisitionCost", "CurrencyId", "AcquisitionDate", "CreatedAt") FROM stdin;
1	1	100000.0000	2	2024-03-15 00:00:00+00	2026-09-20 14:02:14.96372+00
2	2	75000.0000	2	2023-08-10 00:00:00+00	2026-09-20 14:02:14.96372+00
3	3	85000.0000	1	2022-11-20 00:00:00+00	2026-09-20 14:02:14.96372+00
4	4	150000.0000	3	2021-06-05 00:00:00+00	2026-09-20 14:02:14.96372+00
5	5	45000.0000	4	2025-01-12 00:00:00+00	2026-09-20 14:02:14.96372+00
\.


--
-- Data for Name: Companies; Type: TABLE DATA; Schema: public; Owner: maintenance_user
--

COPY public."Companies" ("CompanyId", "CompanyCode", "CompanyName", "CountryId", "IsActive", "CreatedAt", "UpdatedAt") FROM stdin;
1	LANKA01	Lanka Industrial Services	1	t	2026-09-20 13:58:40.692217+00	2026-09-20 13:58:40.692217+00
2	UKIND01	UK Industrial Services	2	t	2026-09-20 13:58:40.692217+00	2026-09-20 13:58:40.692217+00
3	AUSIND01	Australia Industrial Services	4	t	2026-09-20 13:58:40.692217+00	2026-09-20 13:58:40.692217+00
\.


--
-- Data for Name: Countries; Type: TABLE DATA; Schema: public; Owner: maintenance_user
--

COPY public."Countries" ("CountryId", "CountryCode", "CountryName", "IsActive") FROM stdin;
1	LK	Sri Lanka	t
2	GB	United Kingdom	t
3	US	United States	t
4	AU	Australia	t
5	DE	Germany	t
6	FR	France	t
\.


--
-- Data for Name: Currencies; Type: TABLE DATA; Schema: public; Owner: maintenance_user
--

COPY public."Currencies" ("CurrencyId", "CurrencyCode", "CurrencyName", "Symbol", "DecimalPlaces", "IsDefault", "IsActive") FROM stdin;
1	LKR	Sri Lankan Rupee	Rs	2	t	t
2	GBP	British Pound	£	2	f	t
3	USD	US Dollar	$	2	f	t
4	AUD	Australian Dollar	A$	2	f	t
5	EUR	Euro	€	2	f	t
\.


--
-- Data for Name: Depreciations; Type: TABLE DATA; Schema: public; Owner: maintenance_user
--

COPY public."Depreciations" ("DepreciationId", "EquipmentId", "DepreciationDate", "DepreciationAmount", "AccumulatedAmount", "CurrencyId", "Method", "CreatedAt") FROM stdin;
1	1	2024-12-31 00:00:00+00	10000.0000	10000.0000	2	Straight-Line	2026-09-20 14:03:25.686929+00
2	1	2025-12-31 00:00:00+00	10000.0000	20000.0000	2	Straight-Line	2026-09-20 14:03:25.686929+00
3	1	2026-12-31 00:00:00+00	10000.0000	30000.0000	2	Straight-Line	2026-09-20 14:03:25.686929+00
4	2	2024-12-31 00:00:00+00	7500.0000	7500.0000	2	Straight-Line	2026-09-20 14:03:25.686929+00
5	2	2025-12-31 00:00:00+00	7500.0000	15000.0000	2	Straight-Line	2026-09-20 14:03:25.686929+00
6	3	2023-12-31 00:00:00+00	8500.0000	8500.0000	1	Straight-Line	2026-09-20 14:03:25.686929+00
7	3	2024-12-31 00:00:00+00	8500.0000	17000.0000	1	Straight-Line	2026-09-20 14:03:25.686929+00
8	4	2022-12-31 00:00:00+00	15000.0000	15000.0000	3	Straight-Line	2026-09-20 14:03:25.686929+00
9	4	2023-12-31 00:00:00+00	15000.0000	30000.0000	3	Straight-Line	2026-09-20 14:03:25.686929+00
10	5	2025-12-31 00:00:00+00	4500.0000	4500.0000	4	Straight-Line	2026-09-20 14:03:25.686929+00
\.


--
-- Data for Name: Equipment; Type: TABLE DATA; Schema: public; Owner: maintenance_user
--

COPY public."Equipment" ("EquipmentId", "SiteId", "EquipmentCode", "EquipmentName", "Description", "SerialNumber", "Manufacturer", "ModelNumber", "EquipmentStatus", "AcquisitionDate", "CreatedAt", "UpdatedAt") FROM stdin;
2	1	EQ-LKA-002	Industrial Air Compressor	Compressed air system for production equipment	SN-COMP-001	Atlas Copco	GA-75	Operational	2023-08-10 00:00:00+00	2026-09-20 14:00:11.132904+00	2026-09-20 14:00:11.132904+00
3	2	EQ-LKA-003	Hydraulic Press	Hydraulic press used for component forming	SN-PRESS-001	Bosch Rexroth	HP-250	Operational	2022-11-20 00:00:00+00	2026-09-20 14:00:11.132904+00	2026-09-20 14:00:11.132904+00
4	3	EQ-UK-001	Industrial Generator	Backup generator for the London facility	SN-GEN-001	Caterpillar	C18	Operational	2021-06-05 00:00:00+00	2026-09-20 14:00:11.132904+00	2026-09-20 14:00:11.132904+00
5	4	EQ-AUS-001	Forklift	Material handling forklift	SN-FORK-001	Toyota	8FG25	Operational	2025-01-12 00:00:00+00	2026-09-20 14:00:11.132904+00	2026-09-20 14:00:11.132904+00
7	1	EQ-LKA-UI-001	UI Test Generator					Operational	\N	2026-09-22 15:07:26.397562+00	2026-09-22 15:07:26.397635+00
1	1	EQ-LKA-001	CNC Milling Machine	Primary CNC milling machine for production - updated	SN-CNC-001	Mazak	VMC-500	Operational	2024-03-15 00:00:00+00	2026-09-20 14:00:11.132904+00	2026-09-23 10:30:03.984495+00
\.


--
-- Data for Name: InflationIndexes; Type: TABLE DATA; Schema: public; Owner: maintenance_user
--

COPY public."InflationIndexes" ("InflationIndexId", "CountryId", "PeriodStart", "PeriodEnd", "IndexValue", "Source", "CreatedAt") FROM stdin;
1	1	2024-01-01 00:00:00+00	2024-12-31 00:00:00+00	1.000000	Demo Data	2026-09-20 14:04:24.296302+00
2	1	2025-01-01 00:00:00+00	2025-12-31 00:00:00+00	1.080000	Demo Data	2026-09-20 14:04:24.296302+00
3	1	2026-01-01 00:00:00+00	2026-12-31 00:00:00+00	1.150000	Demo Data	2026-09-20 14:04:24.296302+00
4	2	2024-01-01 00:00:00+00	2024-12-31 00:00:00+00	1.000000	Demo Data	2026-09-20 14:04:24.296302+00
5	2	2025-01-01 00:00:00+00	2025-12-31 00:00:00+00	1.030000	Demo Data	2026-09-20 14:04:24.296302+00
6	2	2026-01-01 00:00:00+00	2026-12-31 00:00:00+00	1.060000	Demo Data	2026-09-20 14:04:24.296302+00
7	3	2024-01-01 00:00:00+00	2024-12-31 00:00:00+00	1.000000	Demo Data	2026-09-20 14:04:24.296302+00
8	3	2025-01-01 00:00:00+00	2025-12-31 00:00:00+00	1.025000	Demo Data	2026-09-20 14:04:24.296302+00
9	3	2026-01-01 00:00:00+00	2026-12-31 00:00:00+00	1.050000	Demo Data	2026-09-20 14:04:24.296302+00
10	4	2024-01-01 00:00:00+00	2024-12-31 00:00:00+00	1.000000	Demo Data	2026-09-20 14:04:24.296302+00
11	4	2025-01-01 00:00:00+00	2025-12-31 00:00:00+00	1.030000	Demo Data	2026-09-20 14:04:24.296302+00
12	4	2026-01-01 00:00:00+00	2026-12-31 00:00:00+00	1.060000	Demo Data	2026-09-20 14:04:24.296302+00
13	5	2024-01-01 00:00:00+00	2024-12-31 00:00:00+00	1.000000	Demo Data	2026-09-20 14:04:24.296302+00
14	5	2025-01-01 00:00:00+00	2025-12-31 00:00:00+00	1.025000	Demo Data	2026-09-20 14:04:24.296302+00
15	5	2026-01-01 00:00:00+00	2026-12-31 00:00:00+00	1.050000	Demo Data	2026-09-20 14:04:24.296302+00
16	6	2024-01-01 00:00:00+00	2024-12-31 00:00:00+00	1.000000	Demo Data	2026-09-20 14:04:24.296302+00
17	6	2025-01-01 00:00:00+00	2025-12-31 00:00:00+00	1.025000	Demo Data	2026-09-20 14:04:24.296302+00
18	6	2026-01-01 00:00:00+00	2026-12-31 00:00:00+00	1.050000	Demo Data	2026-09-20 14:04:24.296302+00
\.


--
-- Data for Name: MaintenanceRequests; Type: TABLE DATA; Schema: public; Owner: maintenance_user
--

COPY public."MaintenanceRequests" ("MaintenanceRequestId", "EquipmentId", "RequestNumber", "Title", "Description", "Priority", "Status", "RequestedAt", "CompletedAt", "CreatedAt", "UpdatedAt") FROM stdin;
1	1	MR-2026-0001	CNC spindle vibration	Excessive vibration detected during spindle operation.	High	Open	2026-09-18 14:00:50.011128+00	\N	2026-09-20 14:00:50.011128+00	2026-09-20 14:00:50.011128+00
2	2	MR-2026-0002	Compressor pressure drop	Air compressor is not maintaining the required pressure.	Critical	In Progress	2026-09-15 14:00:50.011128+00	\N	2026-09-20 14:00:50.011128+00	2026-09-20 14:00:50.011128+00
3	3	MR-2026-0003	Hydraulic oil replacement	Scheduled hydraulic oil replacement.	Medium	Completed	2026-09-10 14:00:50.011128+00	2026-09-12 14:00:50.011128+00	2026-09-20 14:00:50.011128+00	2026-09-20 14:00:50.011128+00
4	4	MR-2026-0004	Generator battery inspection	Backup generator battery requires inspection.	Low	Open	2026-09-19 14:00:50.011128+00	\N	2026-09-20 14:00:50.011128+00	2026-09-20 14:00:50.011128+00
5	5	MR-2026-0005	Forklift brake issue	Brake performance is below the expected operating level.	High	In Progress	2026-09-17 14:00:50.011128+00	\N	2026-09-20 14:00:50.011128+00	2026-09-20 14:00:50.011128+00
7	7	5473	genarator test	test	Critical	Open	2026-09-23 17:31:00+00	\N	2026-09-23 10:33:11.612872+00	2026-09-23 10:33:11.612872+00
\.


--
-- Data for Name: Sites; Type: TABLE DATA; Schema: public; Owner: maintenance_user
--

COPY public."Sites" ("SiteId", "CompanyId", "SiteCode", "SiteName", "CountryId", "AddressLine1", "AddressLine2", "City", "PostalCode", "IsActive", "CreatedAt", "UpdatedAt") FROM stdin;
1	1	LKA01	Colombo Main Site	1	100 Industrial Road	\N	Colombo	00100	t	2026-09-20 13:59:32.465377+00	2026-09-20 13:59:32.465377+00
2	1	LKA02	Kandy Service Site	1	25 Industrial Park	\N	Kandy	20000	t	2026-09-20 13:59:32.465377+00	2026-09-20 13:59:32.465377+00
3	2	UK01	London Operations	2	50 Industrial Estate	\N	London	EC1A 1AA	t	2026-09-20 13:59:32.465377+00	2026-09-20 13:59:32.465377+00
4	3	AUS01	Sydney Operations	4	10 Industrial Drive	\N	Sydney	2000	t	2026-09-20 13:59:32.465377+00	2026-09-20 13:59:32.465377+00
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: maintenance_user
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260920134825_InitialCreate	10.0.12
20260920141256_AddInflationIndexPeriodCheck	10.0.12
\.


--
-- Name: AssetValuations_AssetValuationId_seq; Type: SEQUENCE SET; Schema: public; Owner: maintenance_user
--

SELECT pg_catalog.setval('public."AssetValuations_AssetValuationId_seq"', 6, true);


--
-- Name: AssetValues_AssetValueId_seq; Type: SEQUENCE SET; Schema: public; Owner: maintenance_user
--

SELECT pg_catalog.setval('public."AssetValues_AssetValueId_seq"', 6, true);


--
-- Name: Companies_CompanyId_seq; Type: SEQUENCE SET; Schema: public; Owner: maintenance_user
--

SELECT pg_catalog.setval('public."Companies_CompanyId_seq"', 3, true);


--
-- Name: Countries_CountryId_seq; Type: SEQUENCE SET; Schema: public; Owner: maintenance_user
--

SELECT pg_catalog.setval('public."Countries_CountryId_seq"', 6, true);


--
-- Name: Currencies_CurrencyId_seq; Type: SEQUENCE SET; Schema: public; Owner: maintenance_user
--

SELECT pg_catalog.setval('public."Currencies_CurrencyId_seq"', 5, true);


--
-- Name: Depreciations_DepreciationId_seq; Type: SEQUENCE SET; Schema: public; Owner: maintenance_user
--

SELECT pg_catalog.setval('public."Depreciations_DepreciationId_seq"', 10, true);


--
-- Name: Equipment_EquipmentId_seq; Type: SEQUENCE SET; Schema: public; Owner: maintenance_user
--

SELECT pg_catalog.setval('public."Equipment_EquipmentId_seq"', 8, true);


--
-- Name: InflationIndexes_InflationIndexId_seq; Type: SEQUENCE SET; Schema: public; Owner: maintenance_user
--

SELECT pg_catalog.setval('public."InflationIndexes_InflationIndexId_seq"', 19, true);


--
-- Name: MaintenanceRequests_MaintenanceRequestId_seq; Type: SEQUENCE SET; Schema: public; Owner: maintenance_user
--

SELECT pg_catalog.setval('public."MaintenanceRequests_MaintenanceRequestId_seq"', 7, true);


--
-- Name: Sites_SiteId_seq; Type: SEQUENCE SET; Schema: public; Owner: maintenance_user
--

SELECT pg_catalog.setval('public."Sites_SiteId_seq"', 4, true);


--
-- Name: AssetValuations PK_AssetValuations; Type: CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."AssetValuations"
    ADD CONSTRAINT "PK_AssetValuations" PRIMARY KEY ("AssetValuationId");


--
-- Name: AssetValues PK_AssetValues; Type: CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."AssetValues"
    ADD CONSTRAINT "PK_AssetValues" PRIMARY KEY ("AssetValueId");


--
-- Name: Companies PK_Companies; Type: CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."Companies"
    ADD CONSTRAINT "PK_Companies" PRIMARY KEY ("CompanyId");


--
-- Name: Countries PK_Countries; Type: CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."Countries"
    ADD CONSTRAINT "PK_Countries" PRIMARY KEY ("CountryId");


--
-- Name: Currencies PK_Currencies; Type: CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."Currencies"
    ADD CONSTRAINT "PK_Currencies" PRIMARY KEY ("CurrencyId");


--
-- Name: Depreciations PK_Depreciations; Type: CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."Depreciations"
    ADD CONSTRAINT "PK_Depreciations" PRIMARY KEY ("DepreciationId");


--
-- Name: Equipment PK_Equipment; Type: CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."Equipment"
    ADD CONSTRAINT "PK_Equipment" PRIMARY KEY ("EquipmentId");


--
-- Name: InflationIndexes PK_InflationIndexes; Type: CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."InflationIndexes"
    ADD CONSTRAINT "PK_InflationIndexes" PRIMARY KEY ("InflationIndexId");


--
-- Name: MaintenanceRequests PK_MaintenanceRequests; Type: CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."MaintenanceRequests"
    ADD CONSTRAINT "PK_MaintenanceRequests" PRIMARY KEY ("MaintenanceRequestId");


--
-- Name: Sites PK_Sites; Type: CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."Sites"
    ADD CONSTRAINT "PK_Sites" PRIMARY KEY ("SiteId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_AssetValuations_CurrencyId; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE INDEX "IX_AssetValuations_CurrencyId" ON public."AssetValuations" USING btree ("CurrencyId");


--
-- Name: IX_AssetValuations_EquipmentId_ValuationDate; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE INDEX "IX_AssetValuations_EquipmentId_ValuationDate" ON public."AssetValuations" USING btree ("EquipmentId", "ValuationDate");


--
-- Name: IX_AssetValues_CurrencyId; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE INDEX "IX_AssetValues_CurrencyId" ON public."AssetValues" USING btree ("CurrencyId");


--
-- Name: IX_AssetValues_EquipmentId; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE UNIQUE INDEX "IX_AssetValues_EquipmentId" ON public."AssetValues" USING btree ("EquipmentId");


--
-- Name: IX_Companies_CompanyCode; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE UNIQUE INDEX "IX_Companies_CompanyCode" ON public."Companies" USING btree ("CompanyCode");


--
-- Name: IX_Companies_CountryId; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE INDEX "IX_Companies_CountryId" ON public."Companies" USING btree ("CountryId");


--
-- Name: IX_Countries_CountryCode; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE UNIQUE INDEX "IX_Countries_CountryCode" ON public."Countries" USING btree ("CountryCode");


--
-- Name: IX_Countries_CountryName; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE UNIQUE INDEX "IX_Countries_CountryName" ON public."Countries" USING btree ("CountryName");


--
-- Name: IX_Currencies_CurrencyCode; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE UNIQUE INDEX "IX_Currencies_CurrencyCode" ON public."Currencies" USING btree ("CurrencyCode");


--
-- Name: IX_Currencies_IsDefault; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE UNIQUE INDEX "IX_Currencies_IsDefault" ON public."Currencies" USING btree ("IsDefault") WHERE ("IsDefault" = true);


--
-- Name: IX_Depreciations_CurrencyId; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE INDEX "IX_Depreciations_CurrencyId" ON public."Depreciations" USING btree ("CurrencyId");


--
-- Name: IX_Depreciations_EquipmentId_DepreciationDate; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE INDEX "IX_Depreciations_EquipmentId_DepreciationDate" ON public."Depreciations" USING btree ("EquipmentId", "DepreciationDate");


--
-- Name: IX_Equipment_SerialNumber; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE UNIQUE INDEX "IX_Equipment_SerialNumber" ON public."Equipment" USING btree ("SerialNumber");


--
-- Name: IX_Equipment_SiteId_EquipmentCode; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE UNIQUE INDEX "IX_Equipment_SiteId_EquipmentCode" ON public."Equipment" USING btree ("SiteId", "EquipmentCode");


--
-- Name: IX_InflationIndexes_CountryId_PeriodStart_PeriodEnd; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE UNIQUE INDEX "IX_InflationIndexes_CountryId_PeriodStart_PeriodEnd" ON public."InflationIndexes" USING btree ("CountryId", "PeriodStart", "PeriodEnd");


--
-- Name: IX_MaintenanceRequests_EquipmentId_Status; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE INDEX "IX_MaintenanceRequests_EquipmentId_Status" ON public."MaintenanceRequests" USING btree ("EquipmentId", "Status");


--
-- Name: IX_MaintenanceRequests_RequestNumber; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE UNIQUE INDEX "IX_MaintenanceRequests_RequestNumber" ON public."MaintenanceRequests" USING btree ("RequestNumber");


--
-- Name: IX_Sites_CompanyId_SiteCode; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE UNIQUE INDEX "IX_Sites_CompanyId_SiteCode" ON public."Sites" USING btree ("CompanyId", "SiteCode");


--
-- Name: IX_Sites_CountryId; Type: INDEX; Schema: public; Owner: maintenance_user
--

CREATE INDEX "IX_Sites_CountryId" ON public."Sites" USING btree ("CountryId");


--
-- Name: AssetValuations FK_AssetValuations_Currencies_CurrencyId; Type: FK CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."AssetValuations"
    ADD CONSTRAINT "FK_AssetValuations_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES public."Currencies"("CurrencyId") ON DELETE RESTRICT;


--
-- Name: AssetValuations FK_AssetValuations_Equipment_EquipmentId; Type: FK CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."AssetValuations"
    ADD CONSTRAINT "FK_AssetValuations_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES public."Equipment"("EquipmentId") ON DELETE RESTRICT;


--
-- Name: AssetValues FK_AssetValues_Currencies_CurrencyId; Type: FK CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."AssetValues"
    ADD CONSTRAINT "FK_AssetValues_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES public."Currencies"("CurrencyId") ON DELETE RESTRICT;


--
-- Name: AssetValues FK_AssetValues_Equipment_EquipmentId; Type: FK CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."AssetValues"
    ADD CONSTRAINT "FK_AssetValues_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES public."Equipment"("EquipmentId") ON DELETE RESTRICT;


--
-- Name: Companies FK_Companies_Countries_CountryId; Type: FK CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."Companies"
    ADD CONSTRAINT "FK_Companies_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES public."Countries"("CountryId") ON DELETE RESTRICT;


--
-- Name: Depreciations FK_Depreciations_Currencies_CurrencyId; Type: FK CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."Depreciations"
    ADD CONSTRAINT "FK_Depreciations_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES public."Currencies"("CurrencyId") ON DELETE RESTRICT;


--
-- Name: Depreciations FK_Depreciations_Equipment_EquipmentId; Type: FK CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."Depreciations"
    ADD CONSTRAINT "FK_Depreciations_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES public."Equipment"("EquipmentId") ON DELETE RESTRICT;


--
-- Name: Equipment FK_Equipment_Sites_SiteId; Type: FK CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."Equipment"
    ADD CONSTRAINT "FK_Equipment_Sites_SiteId" FOREIGN KEY ("SiteId") REFERENCES public."Sites"("SiteId") ON DELETE RESTRICT;


--
-- Name: InflationIndexes FK_InflationIndexes_Countries_CountryId; Type: FK CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."InflationIndexes"
    ADD CONSTRAINT "FK_InflationIndexes_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES public."Countries"("CountryId") ON DELETE RESTRICT;


--
-- Name: MaintenanceRequests FK_MaintenanceRequests_Equipment_EquipmentId; Type: FK CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."MaintenanceRequests"
    ADD CONSTRAINT "FK_MaintenanceRequests_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES public."Equipment"("EquipmentId") ON DELETE RESTRICT;


--
-- Name: Sites FK_Sites_Companies_CompanyId; Type: FK CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."Sites"
    ADD CONSTRAINT "FK_Sites_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES public."Companies"("CompanyId") ON DELETE RESTRICT;


--
-- Name: Sites FK_Sites_Countries_CountryId; Type: FK CONSTRAINT; Schema: public; Owner: maintenance_user
--

ALTER TABLE ONLY public."Sites"
    ADD CONSTRAINT "FK_Sites_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES public."Countries"("CountryId") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict ldgzxKQJyVKhz7jfcOlAa2SFb9edJcVEmkOMngUf9W0HCvJbXK0e01EshemhIqp

