CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Countries" (
    "CountryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CountryCode" character varying(2) NOT NULL,
    "CountryName" character varying(100) NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Countries" PRIMARY KEY ("CountryId")
);

CREATE TABLE "Currencies" (
    "CurrencyId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CurrencyCode" character varying(3) NOT NULL,
    "CurrencyName" character varying(100) NOT NULL,
    "Symbol" character varying(10) NOT NULL,
    "DecimalPlaces" smallint NOT NULL,
    "IsDefault" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Currencies" PRIMARY KEY ("CurrencyId")
);

CREATE TABLE "Companies" (
    "CompanyId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyCode" character varying(50) NOT NULL,
    "CompanyName" character varying(200) NOT NULL,
    "CountryId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Companies" PRIMARY KEY ("CompanyId"),
    CONSTRAINT "FK_Companies_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Countries" ("CountryId") ON DELETE RESTRICT
);

CREATE TABLE "InflationIndexes" (
    "InflationIndexId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CountryId" integer NOT NULL,
    "PeriodStart" timestamp with time zone NOT NULL,
    "PeriodEnd" timestamp with time zone NOT NULL,
    "IndexValue" numeric(19,6) NOT NULL,
    "Source" character varying(200),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InflationIndexes" PRIMARY KEY ("InflationIndexId"),
    CONSTRAINT "FK_InflationIndexes_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Countries" ("CountryId") ON DELETE RESTRICT
);

CREATE TABLE "Sites" (
    "SiteId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "SiteCode" character varying(50) NOT NULL,
    "SiteName" character varying(200) NOT NULL,
    "CountryId" integer NOT NULL,
    "AddressLine1" character varying(250) NOT NULL,
    "AddressLine2" character varying(250),
    "City" character varying(100) NOT NULL,
    "PostalCode" character varying(30),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Sites" PRIMARY KEY ("SiteId"),
    CONSTRAINT "FK_Sites_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("CompanyId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Sites_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Countries" ("CountryId") ON DELETE RESTRICT
);

CREATE TABLE "Equipment" (
    "EquipmentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "SiteId" integer NOT NULL,
    "EquipmentCode" character varying(50) NOT NULL,
    "EquipmentName" character varying(200) NOT NULL,
    "Description" text,
    "SerialNumber" character varying(100),
    "Manufacturer" character varying(150),
    "ModelNumber" character varying(100),
    "EquipmentStatus" character varying(30) NOT NULL,
    "AcquisitionDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Equipment" PRIMARY KEY ("EquipmentId"),
    CONSTRAINT "FK_Equipment_Sites_SiteId" FOREIGN KEY ("SiteId") REFERENCES "Sites" ("SiteId") ON DELETE RESTRICT
);

CREATE TABLE "AssetValuations" (
    "AssetValuationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "EquipmentId" integer NOT NULL,
    "ValuationDate" timestamp with time zone NOT NULL,
    "ValuationAmount" numeric(19,4) NOT NULL,
    "CurrencyId" integer NOT NULL,
    "ValuationType" character varying(30) NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AssetValuations" PRIMARY KEY ("AssetValuationId"),
    CONSTRAINT "FK_AssetValuations_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("CurrencyId") ON DELETE RESTRICT,
    CONSTRAINT "FK_AssetValuations_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("EquipmentId") ON DELETE RESTRICT
);

CREATE TABLE "AssetValues" (
    "AssetValueId" integer GENERATED BY DEFAULT AS IDENTITY,
    "EquipmentId" integer NOT NULL,
    "AcquisitionCost" numeric(19,4) NOT NULL,
    "CurrencyId" integer NOT NULL,
    "AcquisitionDate" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AssetValues" PRIMARY KEY ("AssetValueId"),
    CONSTRAINT "FK_AssetValues_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("CurrencyId") ON DELETE RESTRICT,
    CONSTRAINT "FK_AssetValues_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("EquipmentId") ON DELETE RESTRICT
);

CREATE TABLE "Depreciations" (
    "DepreciationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "EquipmentId" integer NOT NULL,
    "DepreciationDate" timestamp with time zone NOT NULL,
    "DepreciationAmount" numeric(19,4) NOT NULL,
    "AccumulatedAmount" numeric(19,4) NOT NULL,
    "CurrencyId" integer NOT NULL,
    "Method" character varying(30) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Depreciations" PRIMARY KEY ("DepreciationId"),
    CONSTRAINT "FK_Depreciations_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("CurrencyId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Depreciations_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("EquipmentId") ON DELETE RESTRICT
);

CREATE TABLE "MaintenanceRequests" (
    "MaintenanceRequestId" integer GENERATED BY DEFAULT AS IDENTITY,
    "EquipmentId" integer NOT NULL,
    "RequestNumber" character varying(50) NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "Priority" character varying(30) NOT NULL,
    "Status" character varying(30) NOT NULL,
    "RequestedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MaintenanceRequests" PRIMARY KEY ("MaintenanceRequestId"),
    CONSTRAINT "FK_MaintenanceRequests_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("EquipmentId") ON DELETE RESTRICT
);

CREATE INDEX "IX_AssetValuations_CurrencyId" ON "AssetValuations" ("CurrencyId");

CREATE INDEX "IX_AssetValuations_EquipmentId_ValuationDate" ON "AssetValuations" ("EquipmentId", "ValuationDate");

CREATE INDEX "IX_AssetValues_CurrencyId" ON "AssetValues" ("CurrencyId");

CREATE UNIQUE INDEX "IX_AssetValues_EquipmentId" ON "AssetValues" ("EquipmentId");

CREATE UNIQUE INDEX "IX_Companies_CompanyCode" ON "Companies" ("CompanyCode");

CREATE INDEX "IX_Companies_CountryId" ON "Companies" ("CountryId");

CREATE UNIQUE INDEX "IX_Countries_CountryCode" ON "Countries" ("CountryCode");

CREATE UNIQUE INDEX "IX_Countries_CountryName" ON "Countries" ("CountryName");

CREATE UNIQUE INDEX "IX_Currencies_CurrencyCode" ON "Currencies" ("CurrencyCode");

CREATE UNIQUE INDEX "IX_Currencies_IsDefault" ON "Currencies" ("IsDefault") WHERE "IsDefault" = true;

CREATE INDEX "IX_Depreciations_CurrencyId" ON "Depreciations" ("CurrencyId");

CREATE INDEX "IX_Depreciations_EquipmentId_DepreciationDate" ON "Depreciations" ("EquipmentId", "DepreciationDate");

CREATE UNIQUE INDEX "IX_Equipment_SerialNumber" ON "Equipment" ("SerialNumber");

CREATE UNIQUE INDEX "IX_Equipment_SiteId_EquipmentCode" ON "Equipment" ("SiteId", "EquipmentCode");

CREATE UNIQUE INDEX "IX_InflationIndexes_CountryId_PeriodStart_PeriodEnd" ON "InflationIndexes" ("CountryId", "PeriodStart", "PeriodEnd");

CREATE INDEX "IX_MaintenanceRequests_EquipmentId_Status" ON "MaintenanceRequests" ("EquipmentId", "Status");

CREATE UNIQUE INDEX "IX_MaintenanceRequests_RequestNumber" ON "MaintenanceRequests" ("RequestNumber");

CREATE UNIQUE INDEX "IX_Sites_CompanyId_SiteCode" ON "Sites" ("CompanyId", "SiteCode");

CREATE INDEX "IX_Sites_CountryId" ON "Sites" ("CountryId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260920134825_InitialCreate', '10.0.12');

COMMIT;

